# Generated by Django 4.2.5 on 2023-10-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzasize',
            old_name='pizza_item',
            new_name='pizza',
        ),
    ]
