# Generated by Django 4.2.5 on 2023-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas_app', '0003_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.TextField(choices=[('25', '25'), ('35', '35cm'), ('45', '45cm')], default='25'),
        ),
    ]
