# Generated by Django 4.2.5 on 2023-10-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas_app', '0004_alter_size_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzasize',
            name='percent_increase',
        ),
    ]
